server:
  port: 8081

spring:
  application:
    name: task-execution-service

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/task_execution}
      database: task_execution

    # Redis Configuration
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    # Producer Configuration for CloudEvents
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer
      properties:
        # CloudEvent content mode: structured or binary
        cloudevents.content.mode: structured
        # Enable idempotence for exactly-once semantics
        enable.idempotence: true
        acks: all
        retries: 3
        # Compression
        compression.type: snappy
        # Batching
        linger.ms: 10
        batch.size: 16384

    # Consumer Configuration for CloudEvents
    consumer:
      group-id: task-execution-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.cloudevents.kafka.CloudEventDeserializer
      properties:
        # CloudEvent content mode
        cloudevents.content.mode: structured
        # Concurrency
        max.poll.records: 100
        max.poll.interval.ms: 300000
        session.timeout.ms: 45000
        heartbeat.interval.ms: 3000

    # Listener Configuration
    listener:
      ack-mode: manual
      concurrency: 3
      # Error handling
      type: batch

    # Topic Configuration
    template:
      default-topic: task-events

    # Topics
    topics:
      task-events: task-events
      wave-events: wave-events

  # Spring MVC Configuration
  mvc:
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false
      media-types:
        json: application/json

# Logging Configuration
logging:
  level:
    root: INFO
    com.paklog.wes.task: DEBUG
    com.paklog.task.execution: DEBUG
    org.springframework.kafka: WARN
    org.mongodb.driver: WARN
    io.cloudevents: DEBUG

# Application-specific Configuration
task:
  assignment:
    strategy: DISTANCE_BASED
    auto-assign: true
  queue:
    starvation-prevention: true
    aging-factor: 0.1

# CloudEvents Configuration
cloudevents:
  kafka:
    topic: warehouse-execution.task-execution.events
    source: /wes/task-execution-service

# PakLog Configuration
paklog:
  kafka:
    topics:
      wave-events: warehouse-execution.wave-planning.events
      task-events: warehouse-execution.task-execution.events
    consumer:
      group-id: task-execution-service

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: when-authorized
  health:
    mongo:
      enabled: true
    redis:
      enabled: true
    kafka:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: dev
      service-type: wes
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

# OpenAPI Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
